/**
 * @fileoverview gRPC-Web generated client stub for cryptoDatapkg
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.2
// source: cryptoData.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.cryptoDatapkg = require('./cryptoData_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cryptoDatapkg.FetchCryptoCoinDataClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cryptoDatapkg.FetchCryptoCoinDataPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cryptoDatapkg.Coin,
 *   !proto.cryptoDatapkg.CoinData>}
 */
const methodDescriptor_FetchCryptoCoinData_GetCoinData = new grpc.web.MethodDescriptor(
  '/cryptoDatapkg.FetchCryptoCoinData/GetCoinData',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cryptoDatapkg.Coin,
  proto.cryptoDatapkg.CoinData,
  /**
   * @param {!proto.cryptoDatapkg.Coin} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cryptoDatapkg.CoinData.deserializeBinary
);


/**
 * @param {!proto.cryptoDatapkg.Coin} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cryptoDatapkg.CoinData>}
 *     The XHR Node Readable Stream
 */
proto.cryptoDatapkg.FetchCryptoCoinDataClient.prototype.getCoinData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cryptoDatapkg.FetchCryptoCoinData/GetCoinData',
      request,
      metadata || {},
      methodDescriptor_FetchCryptoCoinData_GetCoinData);
};


/**
 * @param {!proto.cryptoDatapkg.Coin} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cryptoDatapkg.CoinData>}
 *     The XHR Node Readable Stream
 */
proto.cryptoDatapkg.FetchCryptoCoinDataPromiseClient.prototype.getCoinData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cryptoDatapkg.FetchCryptoCoinData/GetCoinData',
      request,
      metadata || {},
      methodDescriptor_FetchCryptoCoinData_GetCoinData);
};


module.exports = proto.cryptoDatapkg;

