// source: cryptoData.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.cryptoDatapkg.Coin', null, global);
goog.exportSymbol('proto.cryptoDatapkg.CoinData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cryptoDatapkg.Coin = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cryptoDatapkg.Coin, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cryptoDatapkg.Coin.displayName = 'proto.cryptoDatapkg.Coin';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cryptoDatapkg.CoinData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cryptoDatapkg.CoinData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cryptoDatapkg.CoinData.displayName = 'proto.cryptoDatapkg.CoinData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cryptoDatapkg.Coin.prototype.toObject = function(opt_includeInstance) {
  return proto.cryptoDatapkg.Coin.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cryptoDatapkg.Coin} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cryptoDatapkg.Coin.toObject = function(includeInstance, msg) {
  var f, obj = {
    coinname: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cryptoDatapkg.Coin}
 */
proto.cryptoDatapkg.Coin.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cryptoDatapkg.Coin;
  return proto.cryptoDatapkg.Coin.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cryptoDatapkg.Coin} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cryptoDatapkg.Coin}
 */
proto.cryptoDatapkg.Coin.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCoinname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cryptoDatapkg.Coin.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cryptoDatapkg.Coin.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cryptoDatapkg.Coin} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cryptoDatapkg.Coin.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCoinname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string coinName = 1;
 * @return {string}
 */
proto.cryptoDatapkg.Coin.prototype.getCoinname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cryptoDatapkg.Coin} returns this
 */
proto.cryptoDatapkg.Coin.prototype.setCoinname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cryptoDatapkg.CoinData.prototype.toObject = function(opt_includeInstance) {
  return proto.cryptoDatapkg.CoinData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cryptoDatapkg.CoinData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cryptoDatapkg.CoinData.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    priceat: jspb.Message.getFieldWithDefault(msg, 2, 0),
    currentprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    arithmeticaggregate: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    geometricaggregate: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    harmonicaggregate: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cryptoDatapkg.CoinData}
 */
proto.cryptoDatapkg.CoinData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cryptoDatapkg.CoinData;
  return proto.cryptoDatapkg.CoinData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cryptoDatapkg.CoinData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cryptoDatapkg.CoinData}
 */
proto.cryptoDatapkg.CoinData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPriceat(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCurrentprice(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setArithmeticaggregate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setGeometricaggregate(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHarmonicaggregate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cryptoDatapkg.CoinData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cryptoDatapkg.CoinData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cryptoDatapkg.CoinData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cryptoDatapkg.CoinData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPriceat();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCurrentprice();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getArithmeticaggregate();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getGeometricaggregate();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getHarmonicaggregate();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.cryptoDatapkg.CoinData.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 priceAt = 2;
 * @return {number}
 */
proto.cryptoDatapkg.CoinData.prototype.getPriceat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setPriceat = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float currentPrice = 3;
 * @return {number}
 */
proto.cryptoDatapkg.CoinData.prototype.getCurrentprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setCurrentprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float arithmeticAggregate = 4;
 * @return {number}
 */
proto.cryptoDatapkg.CoinData.prototype.getArithmeticaggregate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setArithmeticaggregate = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float geometricAggregate = 5;
 * @return {number}
 */
proto.cryptoDatapkg.CoinData.prototype.getGeometricaggregate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setGeometricaggregate = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float harmonicAggregate = 6;
 * @return {number}
 */
proto.cryptoDatapkg.CoinData.prototype.getHarmonicaggregate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.cryptoDatapkg.CoinData} returns this
 */
proto.cryptoDatapkg.CoinData.prototype.setHarmonicaggregate = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


goog.object.extend(exports, proto.cryptoDatapkg);
